events {
    worker_connections 1024;
}

http {
    upstream frontend {
        server frontend:8000;
    }
    
    upstream ratings_api {
        server ratings_api:8002;
    }
    
    upstream users_api {
        server users_api:8001;
    }
    
    server {
        listen 80;
        server_name localhost;
        
        # Основной сайт (Django)
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # API лайков
        location /api/rate {
            proxy_pass http://ratings_api/api/rate;
            proxy_set_header Host $host;
        }
        
        location /api/get-ratings {
            proxy_pass http://ratings_api/api/get-ratings;
            proxy_set_header Host $host;
        }
        
        location /api/reset-ratings {
            proxy_pass http://ratings_api/api/reset-ratings;
            proxy_set_header Host $host;
        }
        
        # API пользователей
        location /api/register {
            proxy_pass http://users_api/api/register;
            proxy_set_header Host $host;
        }
        
        location /api/users {
            proxy_pass http://users_api/api/users;
            proxy_set_header Host $host;
        }
        
        # Статика
        location /static/ {
            proxy_pass http://frontend/static/;
        }
    }
}