name: Build Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build frontend
      run: docker build -t my-frontend ./frontend
    
    - name: Build ratings_api
      run: docker build -t my-ratings-api ./ratings_api
    
    - name: Build users_api
      run: docker build -t my-users-api ./users_api
    
    - name: Start containers
      run: docker compose up -d --build  # ← без дефиса
    
    - name: Wait
      run: sleep 10
    
    - name: Test
      run: curl -f http://localhost:8002/health || true
    
    - name: Stop
      run: docker compose down